2024-11-14 23:27:01,041 | WARNING |Не верный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\PYTHON\12.Поддержка_цикла_разработки\tests_12_4.py", line 22, in test_run
    run = Runner(5, 5)
          ^^^^^^^^^^^^
  File "D:\PYTHON\12.Поддержка_цикла_разработки\runner3.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-14 23:27:01,043 | WARNING |Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PYTHON\12.Поддержка_цикла_разработки\tests_12_4.py", line 11, in test_walk
    run = Runner('Вася',-10)
          ^^^^^^^^^^^^^^^^^^
  File "D:\PYTHON\12.Поддержка_цикла_разработки\runner3.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
